### PR TITLE
fixes #7, CxlRejResponseToCodeSet(434), "OrderCancel" should be "Order…

### LINKED ISSUE #7: CxlRejResponseToCodeSet, "OrderCancel" should be "OrderCancelReplaceRequest"
<fixr:codeSet name="CxlRejResponseToCodeSet" id="434" type="char">
			<fixr:code name="OrderCancelRequest" id="434001" value="1" sort="1" added="FIX.4.2">
				<fixr:annotation>
					<fixr:documentation purpose="SYNOPSIS">
         Order cancel request
      </fixr:documentation>
				</fixr:annotation>
			</fixr:code>
			<fixr:code name="OrderCancel" id="434002" value="2" sort="2" added="FIX.4.2">
				<fixr:annotation>
					<fixr:documentation purpose="SYNOPSIS">
         Order cancel/replace request
      </fixr:documentation>
				</fixr:annotation>
			</fixr:code>
			<fixr:annotation>
				<fixr:documentation purpose="SYNOPSIS">
         Identifies the type of request that a Cancel Reject is in response to.
      </fixr:documentation>
			</fixr:annotation>
		</fixr:codeSet>

### PR DESCRIPTION
**Pull request by david-gibbs-ig**
CxlRejResponseToCodeSet(434), "OrderCancel" should be "OrderCancelReplaceRequest"

### CODE REVIEW

**Comment by david-gibbs-ig** [comment]
fixes #7

**Comment by david-gibbs-ig** [comment]
fixes #7

**Comment by david-gibbs-ig** [comment]
fixes #7

**Comment by donmendelson** [comment]
The pull request appears to be correct. However, the change has already been made in EP 204. Rather than back-port corrections to earlier versions of the repository, we have decided to begin publishing Orchestra files that represent FIX Latest. They will also be available from https://www.fixtrading.org/extension-packs/, beginning with EP 255.

**Pull request closed without merging**
